# Libaries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
import numpy as np
import pandas as pd
from src.benchmarks import (
    BenchmarkConfig,
    RidgeConfig,
    PairDatasetBuilder,
    PairwiseElasticityPipeline,
    RegularizedElasticityPipeline,
    BootstrapSummarizer,
)
from src.dominick import DominickDataLoader
from src.utils import TemporalSplitter, BlockBootstrapSampler

In [2]:
TRAIN_FRAC = 0.8
N_FOLDS = 5
N_BOOTSTRAP = 20
SELECTED_UPCS = [3410010505, 1820000784, 7289000011, 8248812345]
config = BenchmarkConfig()

# Loader

In [3]:
loader = DominickDataLoader()
df = loader.load("elasticity_dataset.csv")
df = df[df["upc_code"].isin(SELECTED_UPCS)].copy()

pair_builder = PairDatasetBuilder(control_cols=config.control_cols)
pair_df = pair_builder.build(df)

print(f"Dataset: {df.shape}, Pairs: {pair_df.shape}")

Dataset: (60269, 44), Pairs: (143878, 24)

In [4]:
splitter = TemporalSplitter(week_col="week_id")
pipeline = PairwiseElasticityPipeline(config)
sampler = BlockBootstrapSampler(week_col="week_id", block_size=13, rng=np.random.default_rng(42))
summarizer = BootstrapSummarizer()

In [5]:
train_df, val_df = splitter.single_split(pair_df, train_frac=TRAIN_FRAC)
train_weeks = sorted(train_df["week_id"].unique())

# K-fold

In [6]:
fold_results, fold_predictions = [], []
for fold_idx, (train_fold, val_fold) in enumerate(splitter.expanding_splits(pair_df, N_FOLDS)):
    print(f"Fold {fold_idx} of {N_FOLDS}")
    res, preds = pipeline.run(train_fold, val_fold)
    res["fold"] = fold_idx
    preds["fold"] = fold_idx
    fold_results.append(res)
    fold_predictions.append(preds)

all_folds = pd.concat(fold_results, ignore_index=True)
ok_folds = all_folds[all_folds["status"] == "ok"].copy()
ok_predictions = pd.concat(fold_predictions, ignore_index=True)
print(f"K-fold raw: {len(ok_folds)} rows")
print(f"K-fold predictions raw: {len(ok_predictions)} rows")

Fold 0 of 5
Fold 1 of 5
Fold 2 of 5
Fold 3 of 5
Fold 4 of 5
K-fold raw: 2698 rows
K-fold predictions raw: 75920 rows

# Bootstrap

In [7]:
bootstrap_results = []
for b in range(N_BOOTSTRAP):
    print(f"Bootstrap {b} of {N_BOOTSTRAP}")
    train_bs = sampler.sample(train_df, train_weeks)
    res, _ = pipeline.run(train_bs, val_df)  
    res["bootstrap_run"] = b
    bootstrap_results.append(res)

all_bootstrap = pd.concat(bootstrap_results, ignore_index=True)
ok_bs = all_bootstrap[all_bootstrap["status"] == "ok"].copy()
print(f"Bootstrap raw: {len(ok_bs)} rows")

Bootstrap 0 of 20
Bootstrap 1 of 20
Bootstrap 2 of 20
Bootstrap 3 of 20
Bootstrap 4 of 20
Bootstrap 5 of 20
Bootstrap 6 of 20
Bootstrap 7 of 20
Bootstrap 8 of 20
Bootstrap 9 of 20
Bootstrap 10 of 20
Bootstrap 11 of 20
Bootstrap 12 of 20
Bootstrap 13 of 20
Bootstrap 14 of 20
Bootstrap 15 of 20
Bootstrap 16 of 20
Bootstrap 17 of 20
Bootstrap 18 of 20
Bootstrap 19 of 20
Bootstrap raw: 10880 rows

# Summaries

In [8]:
bootstrap_summary = summarizer.summarize_raw(ok_bs)

print(f"K-fold raw: {len(ok_folds)}")
print(f"Bootstrap summary: {len(bootstrap_summary)}")

K-fold raw: 2698
Bootstrap summary: 544

# Display

In [9]:
display(ok_folds.head(10))
display(ok_folds[["own_elasticity", "cross_elasticity", "mae_val", "rmse_val", "r2_val"]].describe())
display(bootstrap_summary.head(10))
display(all_folds["status"].value_counts(dropna=False))
display(all_bootstrap["status"].value_counts(dropna=False))

,store_code,pair_id,upc_i,upc_j,status,n_train,n_val,own_elasticity,own_elasticity_ci_low,own_elasticity_ci_high,own_elasticity_p_value,cross_elasticity,cross_elasticity_ci_low,cross_elasticity_ci_high,cross_elasticity_p_value,mae_val,rmse_val,r2_val,fold
0,8,1820000784.0__3410010505.0,1820000784,3410010505,ok,140,30,-3.980905,-5.830347,-2.131462,2.456042e-05,-1.234048,-2.646545,0.178449,0.086832,0.538855,0.704073,0.245433,0
1,8,1820000784.0__3410010505.0,3410010505,1820000784,ok,140,30,-4.212563,-6.343453,-2.081673,1.067742e-04,-0.775208,-2.015348,0.464932,0.220512,0.573049,0.698324,-0.213861,0
2,8,1820000784.0__7289000011.0,1820000784,7289000011,ok,101,20,-3.765933,-5.760757,-1.771109,2.154953e-04,-3.926900,-10.769218,2.915418,0.260653,0.589636,0.709794,0.256038,0
3,8,1820000784.0__7289000011.0,7289000011,1820000784,ok,101,20,-2.149943,-9.852645,5.552759,5.843402e-01,-0.882123,-2.169530,0.405285,0.179287,0.512074,0.611032,0.108886,0
4,8,3410010505.0__7289000011.0,3410010505,7289000011,ok,98,20,-4.785439,-7.206190,-2.364688,1.068280e-04,0.245885,-8.862543,9.354312,0.957804,0.460590,0.536123,0.014424,0
5,8,3410010505.0__7289000011.0,7289000011,3410010505,ok,98,20,-2.662915,-10.724248,5.398418,5.173482e-01,-0.158955,-1.795037,1.477127,0.848979,0.508860,0.616540,0.092748,0
6,9,1820000784.0__3410010505.0,1820000784,3410010505,ok,139,30,-5.423891,-7.472305,-3.375477,2.106448e-07,0.137648,-1.809078,2.084374,0.889779,0.532215,0.637518,0.340462,0
7,9,1820000784.0__3410010505.0,3410010505,1820000784,ok,139,30,-5.067243,-6.677684,-3.456801,6.959184e-10,0.964821,-0.880548,2.810190,0.305488,0.848677,0.993671,-2.277983,0
8,9,1820000784.0__7289000011.0,1820000784,7289000011,ok,116,23,-4.980704,-7.098882,-2.862525,4.052383e-06,-1.205629,-9.193661,6.782403,0.767370,0.529073,0.618345,0.295301,0
9,9,1820000784.0__7289000011.0,7289000011,1820000784,ok,116,23,-2.260235,-11.330384,6.809914,6.252573e-01,1.054392,-0.200042,2.308826,0.099473,0.649468,0.832826,-0.169087,0

       own_elasticity  cross_elasticity      mae_val     rmse_val       r2_val
count     2698.000000       2698.000000  2698.000000  2698.000000  2698.000000
mean        -3.644563         -0.284172     0.562144     0.696843    -0.608136
std          2.185580          1.416743     0.317327     0.361035     2.753891
min        -10.465402        -10.249063     0.205045     0.250104   -34.646424
25%         -5.017036         -0.712431     0.413263     0.525973    -0.476647
50%         -3.751471         -0.249894     0.499784     0.628715    -0.048237
75%         -2.283387          0.189723     0.606555     0.756027     0.254203
max         13.449440         15.694139     4.441895     4.968948     0.843516

,store_code,pair_id,upc_i,upc_j,own_elasticity_mean,own_elasticity_std,own_elasticity_ci_low,own_elasticity_ci_high,cross_elasticity_mean,cross_elasticity_std,cross_elasticity_ci_low,cross_elasticity_ci_high,mae_val_mean,mae_val_std,rmse_val_mean,rmse_val_std,r2_val_mean,r2_val_std
0,8,1820000784.0__3410010505.0,1820000784,3410010505,-4.696523,1.017385,-6.794421,-3.403159,-0.267271,0.670394,-1.368746,1.091043,0.555228,0.088706,0.718630,0.078258,-0.081273,0.257116
1,8,1820000784.0__3410010505.0,3410010505,1820000784,-3.468943,0.756681,-5.061746,-2.431358,0.722323,0.855809,-0.293220,2.654460,0.661354,0.116960,0.802915,0.127254,-1.099831,0.692402
2,8,1820000784.0__7289000011.0,1820000784,7289000011,-4.487611,0.684532,-5.658833,-3.304101,-3.441465,1.457615,-6.164020,-0.827173,0.587492,0.070873,0.748245,0.071822,-0.169316,0.231643
3,8,1820000784.0__7289000011.0,7289000011,1820000784,-0.057492,2.108233,-2.974935,3.830139,-0.743988,0.701795,-2.065581,0.521260,1.146700,0.507158,1.318187,0.501430,-3.194143,3.445948
4,8,3410010505.0__7289000011.0,3410010505,7289000011,-3.078688,0.759713,-4.354404,-1.915612,-1.000651,0.720963,-2.369319,0.066753,0.615277,0.114860,0.749189,0.131478,-0.837852,0.658822
5,8,3410010505.0__7289000011.0,7289000011,3410010505,-0.656714,1.925636,-3.472681,2.626137,-0.556747,0.357456,-1.085004,0.084003,1.252261,0.567816,1.412785,0.567508,-3.884748,3.894385
6,9,1820000784.0__3410010505.0,1820000784,3410010505,-4.983914,0.648749,-6.162909,-4.242532,0.439869,0.786008,-0.626078,1.831374,0.753128,0.084175,0.940334,0.087119,-0.988614,0.363222
7,9,1820000784.0__3410010505.0,3410010505,1820000784,-2.982066,0.502018,-3.744229,-1.948957,0.317028,1.325554,-2.074268,2.326637,0.439579,0.083742,0.523686,0.094634,-0.424688,0.558478
8,9,1820000784.0__7289000011.0,1820000784,7289000011,-4.328443,1.129783,-6.263590,-2.937347,-1.442098,1.375459,-3.629841,0.997305,0.721718,0.095457,0.897066,0.107697,-0.819761,0.427687
9,9,1820000784.0__7289000011.0,7289000011,1820000784,-3.711619,1.692236,-6.212874,-0.853812,1.184839,0.552722,0.371576,2.275326,0.421064,0.105313,0.534243,0.122079,0.296013,0.406435

status
ok    2698
Name: count, dtype: int64

status
ok    10880
Name: count, dtype: int64

# Save

In [10]:
ok_folds.to_csv("../data/benchmark_kfold_raw.csv", index=False)
ok_predictions.to_csv("../data/benchmark_kfold_predictions_raw.csv", index=False)
ok_bs.to_csv("../data/benchmark_bootstrap_raw.csv", index=False)
bootstrap_summary.to_csv("../data/benchmark_elasticities_bootstrap_summary.csv", index=False)
print("Saved OK")

Saved OK

# Ridge Benchmark

In [11]:
ridge_config = RidgeConfig()
ridge_pipeline = RegularizedElasticityPipeline(ridge_config)

In [12]:
ridge_fold_results, ridge_fold_predictions = [], []
for fold_idx, (train_fold, val_fold) in enumerate(splitter.expanding_splits(pair_df, N_FOLDS)):
    print(f"[Ridge] Fold {fold_idx} of {N_FOLDS}")
    res, preds = ridge_pipeline.run(train_fold, val_fold)
    res["fold"] = fold_idx
    preds["fold"] = fold_idx
    ridge_fold_results.append(res)
    ridge_fold_predictions.append(preds)

ridge_all_folds = pd.concat(ridge_fold_results, ignore_index=True)
ridge_ok_folds = ridge_all_folds[ridge_all_folds["status"] == "ok"].copy()
ridge_ok_predictions = pd.concat(ridge_fold_predictions, ignore_index=True)
print(f"Ridge K-fold raw: {len(ridge_ok_folds)} rows")
print(f"Ridge K-fold predictions raw: {len(ridge_ok_predictions)} rows")

[Ridge] Fold 0 of 5
[Ridge] Fold 1 of 5
[Ridge] Fold 2 of 5
[Ridge] Fold 3 of 5
[Ridge] Fold 4 of 5
Ridge K-fold raw: 2698 rows
Ridge K-fold predictions raw: 75920 rows

In [13]:
ridge_bootstrap_results = []
for b in range(N_BOOTSTRAP):
    print(f"[Ridge] Bootstrap {b} of {N_BOOTSTRAP}")
    train_bs = sampler.sample(train_df, train_weeks)
    res, _ = ridge_pipeline.run(train_bs, val_df)   
    res["bootstrap_run"] = b
    ridge_bootstrap_results.append(res)

ridge_all_bootstrap = pd.concat(ridge_bootstrap_results, ignore_index=True)
ridge_ok_bs = ridge_all_bootstrap[ridge_all_bootstrap["status"] == "ok"].copy()
print(f"Ridge Bootstrap raw: {len(ridge_ok_bs)} rows")

[Ridge] Bootstrap 0 of 20
[Ridge] Bootstrap 1 of 20
[Ridge] Bootstrap 2 of 20
[Ridge] Bootstrap 3 of 20
[Ridge] Bootstrap 4 of 20
[Ridge] Bootstrap 5 of 20
[Ridge] Bootstrap 6 of 20
[Ridge] Bootstrap 7 of 20
[Ridge] Bootstrap 8 of 20
[Ridge] Bootstrap 9 of 20
[Ridge] Bootstrap 10 of 20
[Ridge] Bootstrap 11 of 20
[Ridge] Bootstrap 12 of 20
[Ridge] Bootstrap 13 of 20
[Ridge] Bootstrap 14 of 20
[Ridge] Bootstrap 15 of 20
[Ridge] Bootstrap 16 of 20
[Ridge] Bootstrap 17 of 20
[Ridge] Bootstrap 18 of 20
[Ridge] Bootstrap 19 of 20
Ridge Bootstrap raw: 10878 rows

In [14]:
ridge_bootstrap_summary = summarizer.summarize_raw(ridge_ok_bs)

ridge_ok_folds.to_csv("../data/benchmark_ridge_kfold_raw.csv", index=False)
ridge_ok_predictions.to_csv("../data/benchmark_ridge_kfold_predictions_raw.csv", index=False)
ridge_ok_bs.to_csv("../data/benchmark_ridge_bootstrap_raw.csv", index=False)
ridge_bootstrap_summary.to_csv("../data/benchmark_ridge_elasticities_bootstrap_summary.csv", index=False)
print("Saved Ridge: kfold_raw, kfold_predictions_raw, bootstrap_raw, bootstrap_summary")

Saved Ridge: kfold_raw, kfold_predictions_raw, bootstrap_raw, bootstrap_summary