# Dominick's Data

## Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent ))

In [2]:
from src.dominick import DominickDataLoader, DominickDataProcessor

## Loader

In [3]:
loader = DominickDataLoader()
df_upc_beer = loader.load("upcber.csv")
df_move_beer = loader.load("wber.csv")

## Join

In [4]:
dataprocessor = DominickDataProcessor()
df_upc_move_beer = dataprocessor.join(df_upc_beer, df_move_beer, on="UPC")
df_upc_move_beer.head()

,COM_CODE,UPC,DESCRIP,SIZE,CASE,NITEM,STORE,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,PRICE_HEX,PROFIT_HEX
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1,4004F5C28F5C28F6,C032D47AE147AE14
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1,4004147AE147AE14,40327851EB851EB8
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1,4003EB851EB851EC,402B333333333333
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1,4007EB851EB851EC,C050F8F5C28F5C29
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1,4003EB851EB851EC,402B333333333333

## Drop HEX

In [5]:
df_upc_move_beer = df_upc_move_beer.drop(columns=["PROFIT_HEX", "PRICE_HEX"])
df_upc_move_beer.head()

,COM_CODE,UPC,DESCRIP,SIZE,CASE,NITEM,STORE,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1

## Renaming

In [6]:
rename_dict = {
    "COM_CODE": "category_code",
    "UPC": "upc_code",
    "DESCRIP": "product_description",
    "SIZE": "pack_size_text",
    "CASE": "units",
    "NITEM": "product_item_code",
    "STORE": "store_code",
    "WEEK": "week_id",
    "MOVE": "units_sold",
    "QTY": "units_per_deal",
    "PRICE": "total_price",
    "SALE": "promo_flag",
    "PROFIT": "gross_margin_pct",
    "OK": "exclude_flag",
}

df_upc_move_beer = dataprocessor.rename(df_upc_move_beer, rename_dict)
df_upc_move_beer.head()

,category_code,upc_code,product_description,pack_size_text,units,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct,exclude_flag
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1

## New Ratios

In [7]:
df_new_ratios = dataprocessor.add_ratios(df_upc_move_beer)
df_new_ratios.head()

,category_code,upc_code,product_description,pack_size_text,units,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct,exclude_flag,unit_price,sales_dolar,gross_margin_rate,gross_margin_dolar,cost_dolar
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1,2.62,28.82,-0.1883,-5.426806,34.246806
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1,2.51,22.59,0.1847,4.172373,18.417627
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1,2.49,14.94,0.1360,2.031840,12.908160
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1,2.99,14.95,-0.6789,-10.149555,25.099555
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1,2.49,2.49,0.1360,0.338640,2.151360