# Dominick's Data

## Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent ))

In [2]:
from src.dominick import DominickDataLoader, DominickDataProcessor, DominickDataSaver

## Loader

In [3]:
loader = DominickDataLoader()
df_upc_beer = loader.load("upcber.csv")
df_move_beer = loader.load("wber.csv")

## Join

In [4]:
dataprocessor = DominickDataProcessor()
df_upc_move_beer = dataprocessor.join(df_upc_beer, df_move_beer, on="UPC")
df_upc_move_beer.head()

,COM_CODE,UPC,DESCRIP,SIZE,CASE,NITEM,STORE,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,PRICE_HEX,PROFIT_HEX
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1,4004F5C28F5C28F6,C032D47AE147AE14
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1,4004147AE147AE14,40327851EB851EB8
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1,4003EB851EB851EC,402B333333333333
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1,4007EB851EB851EC,C050F8F5C28F5C29
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1,4003EB851EB851EC,402B333333333333

## Drop HEX

In [5]:
df_upc_move_beer = df_upc_move_beer.drop(columns=["PROFIT_HEX", "PRICE_HEX"])
df_upc_move_beer.head()

,COM_CODE,UPC,DESCRIP,SIZE,CASE,NITEM,STORE,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1

## Renaming

In [6]:
rename_dict = {
    "COM_CODE": "category_code",
    "UPC": "upc_code",
    "DESCRIP": "product_description",
    "SIZE": "pack_size_text",
    "CASE": "units_per_case",
    "NITEM": "product_item_code",
    "STORE": "store_code",
    "WEEK": "week_id",
    "MOVE": "units_sold",
    "QTY": "units_per_deal",
    "PRICE": "total_price",
    "SALE": "promo_flag",
    "PROFIT": "gross_margin_pct",
    "OK": "exclude_flag",
}

df_upc_move_beer = dataprocessor.rename(df_upc_move_beer, rename_dict)
df_upc_move_beer.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct,exclude_flag
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,1
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,1
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,1
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,1
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,1

# Dominick's Data

> KILTS Center for Marketing: Dominick's Data Manual  
> We do not use flagged data in our analysis. Therefore, we exclude it: `exclude_flag != 0`

In [7]:
df_upc_move_beer_flagged = df_upc_move_beer[df_upc_move_beer["exclude_flag"] != 0].drop(columns=["exclude_flag"])
df_upc_move_beer_flagged.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60

## New Ratios

In [8]:
# Gross-margin / cost ratios derived from the raw dollar columns.
df_new_ratios = dataprocessor.add_ratios(df_upc_move_beer_flagged)
df_new_ratios.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct,unit_price,sales_dolar,gross_margin_rate,gross_margin_dolar,cost_dolar
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,2.62,28.82,-0.1883,-5.43,34.25
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,2.51,22.59,0.1847,4.17,18.42
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,2.49,14.94,0.1360,2.03,12.91
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,2.99,14.95,-0.6789,-10.15,25.10
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,2.49,2.49,0.1360,0.34,2.15

# New Descriptions

In [9]:
# Canonical brand / style labels parsed from product_description.
df_new_descriptions = dataprocessor.add_text_normalization(df_new_ratios)
df_new_descriptions.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,total_price,promo_flag,gross_margin_pct,unit_price,sales_dolar,gross_margin_rate,gross_margin_dolar,cost_dolar,brand_family_norm,style_segment_norm
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,2.62,NaN,-18.83,2.62,28.82,-0.1883,-5.43,34.25,BEER_LIMIT,UNKNOWN_STYLE
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,2.51,NaN,18.47,2.51,22.59,0.1847,4.17,18.42,BEER_LIMIT,UNKNOWN_STYLE
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,2.49,NaN,13.60,2.49,14.94,0.1360,2.03,12.91,BEER_LIMIT,UNKNOWN_STYLE
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,2.99,NaN,-67.89,2.99,14.95,-0.6789,-10.15,25.10,BEER_LIMIT,UNKNOWN_STYLE
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,2.49,NaN,13.60,2.49,2.49,0.1360,0.34,2.15,BEER_LIMIT,UNKNOWN_STYLE

## Elasticity features

In [10]:
# Promo-type flags used later as elasticity covariates.
df_elasticity_features = dataprocessor.add_elasticity_features(df_new_descriptions)
df_elasticity_features.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,...,liters_per_upc,price_per_upc,liters_sold,price_per_liter,on_promo,promo_B,promo_C,promo_S,log_liters_sold,log_price_per_liter
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,...,4.258588,2.62,46.844471,0.6152,False,0,0,0,3.846833,-0.485808
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,...,4.258588,2.51,38.327294,0.5894,False,0,0,0,3.646162,-0.528650
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,...,4.258588,2.49,25.551530,0.5847,False,0,0,0,3.240697,-0.536656
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,...,4.258588,2.99,21.292941,0.7021,False,0,0,0,3.058376,-0.353679
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,...,4.258588,2.49,4.258588,0.5847,False,0,0,0,1.448938,-0.536656

## Save CSV

In [12]:
saver = DominickDataSaver()
saver.save("dominick_features.csv", df_elasticity_features)